name: MicVolumeWidget Build & Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  dll:
    name: Build plugin DLL
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Windows-SDK
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.3'
      - name: Build MakeFile
        run: qmake
      - name: Setting up nmake
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build DLL with MakeFile.Release
        run: nmake -f MakeFile.Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.NEWTAG}}
          release_name: Release ${{env.NEWTAG}}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/QTmicts.dll
          asset_name: MicVolPluginTs3.dll
          asset_content_type: application/zip

      
    



